export interface LegExercisesProps {
  name: string,
  category: 'Full Leg' | 'Quadriceps' | 'Hamstrings' | 'Glutes' | 'Calves',
  videoLink: string,
  description: string,
  sets: string,
  reps: string
}

export const legExercises: LegExercisesProps[] = [
  // Full Leg Exercises
  {
    name: 'Squats',
    category: 'Full Leg',
    videoLink: 'https://www.youtube.com/watch?v=U3vYeZ0wL10',
    description: 'A compound exercise that targets the entire lower body, including quads, hamstrings, glutes, and calves.',
    sets: '1 - 4',
    reps: '1 - 8',
  },
  {
    name: 'Lunges',
    category: 'Full Leg',
    videoLink: 'https://www.youtube.com/watch?v=qSglFJCV5Uk',
    description: 'Another compound exercise that targets the entire lower body, with a focus on quads and glutes.',
    sets: '3 - 4',
    reps: '8 - 12',
  },
  {
    name: 'Deadlifts',
    category: 'Full Leg',
    videoLink: 'https://www.youtube.com/watch?v=op9kVnSso6Q',
    description: 'A great exercise for building overall strength, with a focus on the hamstrings and glutes.',
    sets: '1 - 4',
    reps: '1 - 8',
  },
  // Quadriceps Exercises
  {
    name: 'Leg Press',
    category: 'Quadriceps',
    videoLink: 'https://www.youtube.com/watch?v=IZxyjW7MPJQ',
    description: 'An exercise that targets the quads, with less emphasis on the glutes and hamstrings compared to squats.',
    sets: '2 - 4',
    reps: '8 - 12',
  },
  {
    name: 'Leg Extensions',
    category: 'Quadriceps',
    videoLink: 'https://www.youtube.com/watch?v=YyvSfVjQeL0',
    description: 'An isolation exercise that specifically targets the quads, with minimal involvement from other lower body muscles.',
    sets: '4 - 6',
    reps: '6 - 12',
  },
  {
    name: 'Front Squats',
    category: 'Quadriceps',
    videoLink: 'https://www.youtube.com/watch?v=8m2nL01DvhQ',
    description: 'A variation of the squat that places more emphasis on the quads and less on the glutes and hamstrings.',
    sets: '1 - 3',
    reps: '1 - 8',
  },
  // Hamstring Exercises
  {
    name: 'Romanian Deadlifts',
    category: 'Hamstrings',
    videoLink: 'https://www.youtube.com/watch?v=kkRksw5_Kd4',
    description: 'An exercise that targets the hamstrings, with less emphasis on the glutes and lower back compared to regular deadlifts.',
    sets: '2 - 4',
    reps: '8 - 12',
  },
  {
    name: 'Hyperextentions',
    category: 'Hamstrings',
    videoLink: 'https://www.youtube.com/watch?v=5g_YqUjuGmc',
    description: 'An exercise that targets the hamstrings and glutes, with a focus on the eccentric phase of the movement.',
    sets: '3 - 4',
    reps: '8 - 16',
  },
  {
    name: 'Lying Leg Curls',
    category: 'Hamstrings',
    videoLink: 'https://www.youtube.com/watch?v=OT_Rg-6Ucz0',
    description: 'An isolation exercise that specifically targets the hamstrings, with minimal involvement from other lower body muscles.',
    sets: '3 - 4',
    reps: '8 - 12',
  },
  // Glutes Exercises
  {
    name: 'Hip Thrusts',
    category: 'Glutes',
    videoLink: 'https://www.youtube.com/watch?v=AdG8MuZ3qsw',
    description: 'Targets your glutes. Sit on the ground with a bench behind you, roll a barbell over your hips, and rest your shoulder blades on the bench. Drive through your heels to lift your hips and squeeze your glutes at the top.',
    sets: '1 - 4',
    reps: '1 - 12',
  },
  {
    name: 'Leg Cable Raises',
    category: 'Glutes',
    videoLink: 'https://www.youtube.com/watch?v=4p4dZEGhr4A',
    description: 'A resistance exercise that targets the glutes, hamstrings, and calves. Stand facing the cable machine, attach the ankle cuff to your ankle, and kick your leg back while keeping your knee straight, squeezing your glutes at the top.',
    sets: '2 - 4',
    reps: '6 - 20',
  },
  {
    name: 'Glute Bridges',
    category: 'Glutes',
    videoLink: 'https://www.youtube.com/watch?v=4p4dZEGhr4A',
    description: 'Targets your glutes. Lie on your back with your knees bent, feet flat on the floor, and lift your hips up to create a straight line from your shoulders to your knees. Squeeze your glutes at the top.',
    sets: '2 - 4',
    reps: '6 - 20',
  },
  {
    name: 'Abduction',
    category: 'Glutes',
    videoLink: 'https://www.youtube.com/watch?v=4p4dZEGhr4A',
    description: 'A machine-based exercise that targets the outer thighs and glutes, performed by sitting upright and pushing the legs outward against resistance.',
    sets: '2 - 4',
    reps: '6 - 20',
  },
  {
    name: 'Adduction',
    category: 'Glutes',
    videoLink: 'https://www.youtube.com/watch?v=4p4dZEGhr4A',
    description: 'A machine-based exercise that targets the adductor muscles of the inner thighs, where you sit with your legs positioned inwards and push against the pads with your inner thighs to bring your legs together.',
    sets: '2 - 4',
    reps: '6 - 20',
  },
  // Calves Exercises
  {
    name: 'Calf Raises',
    category: 'Calves',
    videoLink: 'https://www.youtube.com/watch?v=QAkR9DhVkBg',
    description: 'Targets your calves. Stand with your feet shoulder-width apart, rise up onto the balls of your feet, then lower back down.',
    sets: '2 - 4',
    reps: '6 - 12',
  },
  {
    name: 'Jump Rope',
    category: 'Calves',
    videoLink: 'https://www.youtube.com/watch?v=T_B6fOa6CQc',
    description: 'Targets your calves while also providing a cardiovascular workout. Jump rope for a set amount of time or reps.',
    sets: '3 - 5',
    reps: 'As many as you wish',
  },
  {
    name: 'Seated Calf Raises',
    category: 'Calves',
    videoLink: 'https://www.youtube.com/watch?v=cKjHTgJcUeM',
    description: 'Targets your calves. Sit on a bench with your knees bent and a weight on your lap, and lift your heels up off the ground.',
    sets: '2 - 4',
    reps: '6 - 12',
  },
]